packages:
  - packages/*

catalog:
  "@tailwindcss/postcss": ^4.1.16
  "@types/node": ^24.9.1
  "@types/react": ^19.2.2
  "@types/react-dom": ^19.2.2
  next: ^16.0.0
  next-intl: ^4.4.0
  postcss: ^8.5.6
  react: ^19.2.0
  react-dom: ^19.2.0
  tailwindcss: ^4.1.16
  typescript: ^5.9.3
